baseURL = "http://happymunday.online/"
languageCode = "en-us"
title = "Happy Munday Podcast"
paginate = 5
theme = "bulma"
publishDir = "docs"

enableRobotsTXT = true
googleAnalytics = ""
SectionPagesMenu = "main"

[params]
  description = "Great news to start your week"
  powered_by = "Evan Machnic"
